# Generated by Django 5.0 on 2024-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='enter name ...', max_length=120, null=True, verbose_name='enter name ...')),
                ('last_name', models.CharField(blank=True, db_index=True, help_text='enter last name ...', max_length=120, null=True, verbose_name='enter last name ...')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='enter phone ...', max_length=15, null=True, verbose_name='enter phone ...')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='enter email ...', max_length=150, null=True, verbose_name='enter email ...')),
            ],
        ),
    ]
